[package]
name = "image2linetext"
version = "0.1.0"
authors = ["Lee <inbox@leefallat.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
